# Generated by Django 3.2.5 on 2021-07-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('priority', models.IntegerField(choices=[(0, 'unimportant'), (1, 'insignificant'), (2, 'important'), (3, 'Necessary')], default=0)),
                ('status', models.CharField(choices=[('deleted', 'deleted'), ('doing', 'doing'), ('done', 'done'), ('expire', 'expire'), ('archive', 'archive')], default='doing', max_length=10)),
                ('expired', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(default='unknown', to='todo.Category')),
            ],
        ),
    ]
